/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.followers
	 */
	public static final tech.codingclub.helix.tables.Followers FOLLOWERS = tech.codingclub.helix.tables.Followers.FOLLOWERS;

	/**
	 * The table public.member
	 */
	public static final tech.codingclub.helix.tables.Member MEMBER = tech.codingclub.helix.tables.Member.MEMBER;

	/**
	 * The table public.tweets
	 */
	public static final tech.codingclub.helix.tables.Tweets TWEETS = tech.codingclub.helix.tables.Tweets.TWEETS;
}
