/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TweetsRecord extends org.jooq.impl.TableRecordImpl<tech.codingclub.helix.tables.records.TweetsRecord> implements org.jooq.Record4<java.lang.String, java.lang.Long, java.sql.Timestamp, java.lang.Long> {

	private static final long serialVersionUID = -557643967;

	/**
	 * Setter for <code>public.tweets.message</code>.
	 */
	public void setMessage(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.tweets.message</code>.
	 */
	public java.lang.String getMessage() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.tweets.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.tweets.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>public.tweets.created_at</code>.
	 */
	public void setCreatedAt(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.tweets.created_at</code>.
	 */
	public java.sql.Timestamp getCreatedAt() {
		return (java.sql.Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>public.tweets.author_id</code>.
	 */
	public void setAuthorId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.tweets.author_id</code>.
	 */
	public java.lang.Long getAuthorId() {
		return (java.lang.Long) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.Long, java.sql.Timestamp, java.lang.Long> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.Long, java.sql.Timestamp, java.lang.Long> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return tech.codingclub.helix.tables.Tweets.TWEETS.MESSAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return tech.codingclub.helix.tables.Tweets.TWEETS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return tech.codingclub.helix.tables.Tweets.TWEETS.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return tech.codingclub.helix.tables.Tweets.TWEETS.AUTHOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getMessage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getAuthorId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TweetsRecord value1(java.lang.String value) {
		setMessage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TweetsRecord value2(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TweetsRecord value3(java.sql.Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TweetsRecord value4(java.lang.Long value) {
		setAuthorId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TweetsRecord values(java.lang.String value1, java.lang.Long value2, java.sql.Timestamp value3, java.lang.Long value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TweetsRecord
	 */
	public TweetsRecord() {
		super(tech.codingclub.helix.tables.Tweets.TWEETS);
	}

	/**
	 * Create a detached, initialised TweetsRecord
	 */
	public TweetsRecord(java.lang.String message, java.lang.Long id, java.sql.Timestamp createdAt, java.lang.Long authorId) {
		super(tech.codingclub.helix.tables.Tweets.TWEETS);

		setValue(0, message);
		setValue(1, id);
		setValue(2, createdAt);
		setValue(3, authorId);
	}
}
