/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tweets extends org.jooq.impl.TableImpl<tech.codingclub.helix.tables.records.TweetsRecord> {

	private static final long serialVersionUID = 1340073691;

	/**
	 * The singleton instance of <code>public.tweets</code>
	 */
	public static final tech.codingclub.helix.tables.Tweets TWEETS = new tech.codingclub.helix.tables.Tweets();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tech.codingclub.helix.tables.records.TweetsRecord> getRecordType() {
		return tech.codingclub.helix.tables.records.TweetsRecord.class;
	}

	/**
	 * The column <code>public.tweets.message</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.TweetsRecord, java.lang.String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR.length(160), this, "");

	/**
	 * The column <code>public.tweets.id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.TweetsRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.tweets.created_at</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.TweetsRecord, java.sql.Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>public.tweets.author_id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.TweetsRecord, java.lang.Long> AUTHOR_ID = createField("author_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>public.tweets</code> table reference
	 */
	public Tweets() {
		this("tweets", null);
	}

	/**
	 * Create an aliased <code>public.tweets</code> table reference
	 */
	public Tweets(java.lang.String alias) {
		this(alias, tech.codingclub.helix.tables.Tweets.TWEETS);
	}

	private Tweets(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.TweetsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Tweets(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.TweetsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tech.codingclub.helix.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<tech.codingclub.helix.tables.records.TweetsRecord, java.lang.Long> getIdentity() {
		return tech.codingclub.helix.Keys.IDENTITY_TWEETS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tech.codingclub.helix.tables.Tweets as(java.lang.String alias) {
		return new tech.codingclub.helix.tables.Tweets(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tech.codingclub.helix.tables.Tweets rename(java.lang.String name) {
		return new tech.codingclub.helix.tables.Tweets(name, null);
	}
}
